src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TicketRepository::class)
 */
class Ticket
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tickets")
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity=Customer::class, inversedBy="tickets")
     */
    private $customer;

    /**
     * @ORM\ManyToMany(targetEntity=Service::class, inversedBy="tickets")
     */
    private $services;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $statut;

    /**
     * @ORM\Column(type="smallint")
     */
    private $priority;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="ticket")
     */
    private $messages;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fileName;

    public function __construct()
    {
        $this->services = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * @return Collection|Service[]
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    public function addService(Service $service): self
    {
        if (!$this->services->contains($service)) {
            $this->services[] = $service;
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        if ($this->services->contains($service)) {
            $this->services->removeElement($service);
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(int $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setTicket($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getTicket() === $this) {
                $message->setTicket(null);
            }
        }

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function setFileName(string $fileName): self
    {
        $this->fileName = $fileName;

        return $this;
    }
}

src/Controller/TicketController.php
<?php

namespace App\Controller;

use App\Entity\Ticket;
use App\Entity\Message;
use App\Form\TicketFormType;
use App\Form\MessageFormType;
use App\Service\FileUploader;
use App\Repository\TicketRepository;
use App\Repository\MessageRepository;
use App\Repository\ServiceRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/ticket")
 * @Security("is_granted('ROLE_CUSTOMER')")
 */
class TicketController extends AbstractController
{
    /**
     * @Route("/", name="ticket_index", methods={"GET"})
     * @Security("is_granted('ROLE_CUSTOMER')")
     */
    public function index(TicketRepository $ticketRepository, ?UserInterface $user): Response
    {
        return $this->render('ticket/index.html.twig', [
            'tickets' => $this->isGranted($user, "ROLE_CUSTOMER") == ["ROLE_CUSTOMER"] ? $ticketRepository->findBy(["customer" => $user->getCustomer()->getId()]) : $ticketRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ticket_new", methods={"GET","POST"})
     */
    public function new(Request $request, ?UserInterface $user, ServiceRepository $serviceRepository, FileUploader $fileUploader): Response
    {
        $ticket = new Ticket();
        $form = $this->createForm(TicketFormType::class, $ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();

            /**
             * @var UploadedFile $brochureFile
             * Permet l'upload de fichier, en suivant les consignes de la doc de symfony : https://symfony.com/doc/current/controller/upload_file.html
             * Avec la mise ne place de la classe Service : FileUploader.
             */
            $brochureFile = $form->get('fileName')->getData();
            // dd($brochureFile);

            if ($brochureFile) {
                $brochureFileName = $fileUploader->upload($brochureFile);
                $ticket->setFilename($brochureFileName);
            }

            $ticket->setAuthor($user);
            $ticket->setCreatedAt(new \Datetime);
            $ticket->setStatut("A valider");
            $ticket->setPriority(0);
            $ticket->setCustomer($user->getCustomer());
            $ticket->addService($serviceRepository->findOneBy(["name" => "Support client"]));
            $entityManager->persist($ticket);
            $entityManager->flush();

            return $this->redirectToRoute('ticket_index');
        }

        return $this->render('ticket/new.html.twig', [
            'ticket' => $ticket,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ticket_show", methods={"GET", "POST"})
     * @Security("is_granted('ROLE_CUSTOMER')")
     */
    public function show(Request $request, Ticket $ticket, MessageRepository $messageRepository, ?UserInterface $user, FileUploader $fileUploader): Response
    {
        $message = new Message();
        $form = $this->createForm(MessageFormType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();

            $brochureFile = $form->get('fileName')->getData();
            // dd($brochureFile);

            if ($brochureFile) {
                $brochureFileName = $fileUploader->upload($brochureFile);
                $message->setFilename($brochureFileName);
            }

            $message->setAuthor($user);
            $message->setCreatedAt(new \Datetime);
            $message->setTicket($ticket);
            $entityManager->persist($message);
            $entityManager->flush();

            return $this->redirectToRoute('ticket_show', ["id" => $ticket->getId()]);

        }

        return $this->render('ticket/show.html.twig', [
            'message' => $message,
            'ticket' => $ticket,
            'form' => $form->createView(),
            'messages' => $messageRepository->findBy(["ticket" => $ticket->getId()])
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ticket_edit", methods={"GET","POST"})
     * @Security("is_granted('ROLE_ADMIN')")
     */
    public function edit(Request $request, Ticket $ticket): Response
    {
        $form = $this->createForm(TicketFormType::class, $ticket, ['modify_ticket' => 'modify']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $ticket->setUpdatedAt(new \Datetime);
            $entityManager->persist($ticket);
            $entityManager->flush();

            return $this->redirectToRoute('ticket_index');
        }

        return $this->render('ticket/edit.html.twig', [
            'ticket' => $ticket,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ticket_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Ticket $ticket): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ticket->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ticket);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ticket_index');
    }

    /**
     * @Route("/{id}/message", name="ticket_new_message", methods={"GET","POST"})
     */
    public function newMessage(Request $request, Ticket $ticket, ?UserInterface $user, FileUploader $fileUploader): Response
    {
        $message = new Message();
        $form = $this->createForm(MessageFormType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();

            $brochureFile = $form->get('fileName')->getData();
            // dd($brochureFile);

            if ($brochureFile) {
                $brochureFileName = $fileUploader->upload($brochureFile);
                $message->setFilename($brochureFileName);
            }

            $message->setAuthor($user);
            $message->setCreatedAt(new \Datetime);
            $message->setTicket($ticket);
            $entityManager->persist($message);
            $entityManager->flush();
            return $this->redirectToRoute('ticket_show', [$ticket->getId()]);
        }

        return $this->render('ticket/new.html.twig', [
        ]);
    }
}

templates/ticket/_delete_form.html.twig
<form method="post" action="{{ path('ticket_delete', {'id': ticket.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ticket.id) }}">
    <button class="btn btn-outline-danger mt-3">Supprimer</button>
</form>

templates/ticket/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-success">{{ button_label|default('Valider') }}</button>
{{ form_end(form) }}

templates/ticket/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un tickets{% endblock %}

{% block body %}
<div class="container">

    <h1 class="text-center">Modifier un ticket</h1>
    <a href="{{ path('ticket_index') }}" class="btn btn-outline-dark mt-3 mb-3">Retour à la liste</a>
    
    {{ include('ticket/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    
    
    {{ include('ticket/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/ticket/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tout les Tickets{% endblock %}

{% block body %}
<div class="container">

    <h1 class="text-center">Tout les tickets en cours</h1><a href="{{ path('ticket_new') }}" class="btn btn-outline-success mt-3">Créer un nouveau ticket</a>
    {% for ticket in tickets %}
        <div class="card {{ ticket.priority == 0 ? "border-dark" : ticket.priority == 1 ? "border-primary" : ticket.priority == 2 ? "border-warning" : ticket.priority == 3 ? "border-danger" }} mt-5">
            <div class="card-header d-flex">
                <div>
                    {{ ticket.id }}.
                    {% for service in ticket.services %}
                        {{ service }}/
                    {% endfor %}
                </div> 
                <div class="ml-auto d-flex">
                    {% if ticket.fileName != null %}
                        <div class="mr-3 badge badge-primary">
                            fichier joint
                        </div>
                    {% endif %}
                    <div class="badge {{ ticket.priority == 0 ? "badge-dark" : ticket.priority == 1 ? "badge-primary" : ticket.priority == 2 ? "badge-warning" : ticket.priority == 3 ? "badge-danger" }} text-wrap">
                        Priorité : {{ ticket.priority == 0 ? "Nulle" : ticket.priority == 1 ? "Pas urgent" : ticket.priority == 2 ? "A voir rapidement" : ticket.priority == 3 ? "Urgent !" }}
                    </div>
                </div>
            </div>
            <div class="card-body {# {{ ticket.priority == 0 ? "text-dark" : ticket.priority == 1 ? "text-primary" : ticket.priority == 2 ? "text-warning" : ticket.priority == 3 ? "text-danger" }} #}">
                <blockquote class="blockquote mb-0">
                    <h5 class="card-title">
                        {{ ticket.titre }}
                    </h5>
                    <p>{{ ticket.description }}</p>
                    <footer class="blockquote-footer">
                        <a href="{{ path('ticket_show', {'id': ticket.id}) }}" class="btn btn-outline-primary">Détails</a>
                        {% if not is_granted("ROLE_CUSTOMER") or is_granted("ROLE_ADMIN") %}
                            <a href="{{ path('ticket_edit', {'id': ticket.id}) }}" class="btn btn-outline-warning">Modifier</a>
                        {% endif %}
                    </footer>
                </blockquote>
            </div>
        </div>
    {% endfor %}

</div>
{% endblock %}

templates/ticket/message.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau message{% endblock %}

{% block body %}
<div class="container">

    
    <a href="{{ path('ticket_show') }}" class="btn btn-outline-dark">Retourner au ticket</a>
</div>
{% endblock %}

templates/ticket/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ticket{% endblock %}

{% block body %}
<div class="container">

    <h1 class="text-center">Create new Ticket</h1>
    
    {{ include('ticket/_form.html.twig') }}
    
    <a href="{{ path('ticket_index') }}" class="btn btn-outline-dark">Retour à la liste</a>
</div>
{% endblock %}

{% block javascriptsPLus %}
<script src="{{ asset("assets/js/index.js") }}"></script>
{% endblock javascriptsPLus %}

templates/ticket/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails Ticket{% endblock %}

{% block body %}
<div class="container">

    <h1 class="text-center">Ticket</h1 class="text-center">
    <a href="{{ path('ticket_index') }}" class="btn btn-outline-dark">Retour à la liste</a>
    
    <div class="accordion" id="accordion">
        <div class="card {{ ticket.priority == 0 ? "border-dark" : ticket.priority == 1 ? "border-primary" : ticket.priority == 2 ? "border-warning" : ticket.priority == 3 ? "border-danger" }} mt-3">
            <div class="card-header d-flex" id="headingOne">
                <p>{{ ticket.id }}. {{ ticket.titre }}</p>
                {% if ticket.fileName != null %}
                    <a class="ml-3" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">Afficher l'image</a>
                {% endif %}
                <div class="ml-auto badge {{ ticket.priority == 0 ? "badge-dark" : ticket.priority == 1 ? "badge-primary" : ticket.priority == 2 ? "badge-warning" : ticket.priority == 3 ? "badge-danger" }} text-wrap">
                    Priorité : {{ ticket.priority == 0 ? "Nulle" : ticket.priority == 1 ? "Pas urgent" : ticket.priority == 2 ? "A voir rapidement" : ticket.priority == 3 ? "Urgent !" }}
                </div>
            </div>
            <div class="card-body {# {{ ticket.priority == 0 ? "text-dark" : ticket.priority == 1 ? "text-primary" : ticket.priority == 2 ? "text-warning" : ticket.priority == 3 ? "text-danger" }} #}">
                <blockquote class="blockquote mb-0">
                    <p>{{ ticket.description }}</p>
                    <footer class="blockquote-footer d-flex">
                        <div>Écrit le : {{ ticket.updatedAt != null ? ticket.updatedAt|date("Y-m-d H:i:s") : ticket.createdAt|date("Y-m-d H:i:s") }}</div>
                        {% if not is_granted("ROLE_CUSTOMER") or is_granted("ROLE_ADMIN") %}
                            <a href="{{ path('ticket_edit', {'id': ticket.id}) }}" class="btn btn-outline-warning ml-auto">Modifier</a>
                        {% endif %}
                    </footer>
                </blockquote>
            </div>
            {% if ticket.fileName != null %}
                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                    <a href="{{ asset('assets/uploads/files/' ~ ticket.fileName ) }}"><img src="{{ asset('assets/uploads/files/' ~ ticket.fileName ) }}" class="card-img-top" alt="Fichier Joint"></a>
                </div>
            {% endif %}
        </div>
    </div>
    {{ include('ticket/_delete_form.html.twig') }}
    <hr>
    {% for message in messages %}
    <div class="card border-dark mb-3">
        <div class="card-header">
            Commentaire à propos de {{ message.ticket.titre }}
        </div>
        <div class="card-body d-flex">
            <div>
                <blockquote class="blockquote mb-0">
                    <p>{{ message.content }}</p>
                    <footer class="blockquote-footer">
                        Écrit par : {{ message.author }} le {{ message.createdAt|date("Y-m-d") }} a {{  message.createdAt|date("H:i:s") }}
                    </footer>
                </blockquote>
            </div>
            {% if message.fileName != null %}
                <div class="ml-auto">
                    <a href="{{ asset('assets/uploads/files/' ~ message.fileName ) }}"><img src="{{ asset('assets/uploads/files/' ~ message.fileName ) }}" class="card-img-top" alt="Fichier Joint" style="width: 150px; height: auto;"></a>
                </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    {% if message.id != null %}
        <hr>
    {% endif %}
    <h2 class="text-center">Écrire un message</h2>
    <div class="mb-3 border border-dark rounded p-3">
        {{ include('ticket/_form.html.twig', {'button_label': 'Envoyer le message ?'}) }}
    </div>
</div>
{% endblock %}

{% block javascriptsPLus %}
<script src="{{ asset("assets/js/index.js") }}"></script>
{% endblock javascriptsPLus %}